spring.datasource.password=mysqsium33
jwt.secret=W3UipeJYNOciP4yyqQQMM8iK5XW1Kw69Dz4gWx1B/lw=
spring.web.resources.static-locations=file:///C:/Users/gekpa/OneDrive/Desktop/TicketStadio/TicketStadio/frontend/
spring.mvc.static-path-pattern=/**
