const AuthAPI={login:d=>apiFetch('/auth/login',{method:'POST',body:JSON.stringify(d)}),register:d=>apiFetch('/auth/register',{method:'POST',body:JSON.stringify(d)})};
function parseJwt(token){try{return JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));}catch{return null;}}
function getToken(){return localStorage.getItem('jwt_token');}
function isLoggedIn(){return!!getToken();}
function getCurrentUser(){const t=getToken();if(!t)return null;const p=parseJwt(t);if(!p||p.exp*1000<Date.now()){logout();return null;}return{email:p.sub,roles:p.roles||[],isAdmin:(p.roles||[]).includes('ROLE_ADMIN')};}
function logout(){localStorage.removeItem('jwt_token');window.location.href='/login.html';}
function requireAuth(){if(!isLoggedIn()||!getCurrentUser())window.location.href=`/login.html?redirect=${encodeURIComponent(window.location.pathname)}`;}
function requireAdmin(){const u=getCurrentUser();if(!u||!u.isAdmin)window.location.href='/index.html';}
function updateNavbar(){const u=getCurrentUser();const na=document.getElementById('nav-auth'),nu=document.getElementById('nav-user'),nA=document.getElementById('nav-admin');if(!na)return;if(u){na.style.display='none';nu.style.display='flex';if(nA)nA.style.display=u.isAdmin?'flex':'none';const em=document.getElementById('nav-email');if(em)em.textContent=u.email;}else{na.style.display='flex';nu.style.display='none';if(nA)nA.style.display='none';}}
async function handleLogin(event){event.preventDefault();const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value,btn=event.submitter;btn.disabled=true;btn.textContent='Accesso in corso…';try{const res=await AuthAPI.login({email,password});localStorage.setItem('jwt_token',res.token);const p=new URLSearchParams(window.location.search);window.location.href=p.get('redirect')||'/index.html';}catch(err){showToast(err.message,'error');btn.disabled=false;btn.textContent='Accedi';}}
async function handleRegister(event){event.preventDefault();const nome=document.getElementById('nome').value.trim(),cognome=document.getElementById('cognome').value.trim(),email=document.getElementById('email').value.trim(),password=document.getElementById('password').value,confirm=document.getElementById('confirm-password').value,btn=event.submitter;if(password!==confirm){showToast('Le password non coincidono','error');return;}btn.disabled=true;btn.textContent='Registrazione…';try{await AuthAPI.register({nome,cognome,email,password});showToast('Registrazione completata!','success');setTimeout(()=>window.location.href='/login.html',1500);}catch(err){showToast(err.message,'error');btn.disabled=false;btn.textContent='Registrati';}}
